export const ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    CHANGE_PASSWORD: '/auth/change-password',
  },
  PORTAL: {
    DASHBOARD: '/portal/dashboard',
    PROFILE: '/portal/profile',
    PORTFOLIO: '/portal/portfolio',
    COMPANIES: '/portal/companies',
    DOCUMENTS: '/portal/documents',
    NOTIFICATIONS: '/portal/notifications',
    MESSAGES: '/portal/messages',
    OPPORTUNITIES: '/portal/opportunities',
    CAPITAL_CALLS: '/portal/capital-calls',
    PERFORMANCE: '/portal/performance',
    TAX_DOCUMENTS: '/portal/tax-documents',
    COMPLIANCE: '/portal/compliance',
    REPORTS: '/portal/reports',
    SETTINGS: '/portal/settings',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    COMPANIES: '/admin/companies',
    DOCUMENTS: '/admin/documents',
    PORTFOLIOS: '/admin/portfolios',
    OPPORTUNITIES: '/admin/opportunities',
    ANALYTICS: '/admin/analytics',
  },
} as const;
